CC=clang
CXX=gcc
CFLAGS=-I. -I../include -I./third_party/include -shared -Wl,
LIBNDPI=libndpi.so.2.9.0
LDFLAGS=$(CFILE) $(LIBNDPI) -lpcap
SHARE = -soname,ndpi_wrap
SO=ndpi_wrap.so
OBJS = ndpi_wrap.o
CFILE = ndpi_wrap.c
PIC = -fPIC
PREFIX?=/usr/local
.PHONY: all

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)#do something for linux
	SHARE=-install_name,ndpiReader.so
endif

all: $(SO)

$(SO): $(CFILE) $(LIBNDPI)
	$(CXX) $(CFLAGS)$(SHARE) -o $@ $(PIC) $(LDFLAGS)
