{
 "title": "Attacks Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 10 IPs",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  {\n    \"$group\": {\n      \"_id\": \"$src_ip\",\n      \"count\": { \"$sum\": 1 }\n    }\n  },\n  {\n    \"$sort\": { \"count\": -1 }\n  },\n  {\n    \"$limit\": 10\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"IP\": \"$_id\",\n      \"Occurrences\": \"$count\"\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Live Attack Map",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 15, "x": 4, "y": 0 },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  { \"$match\": { \"latitude\": { \"$exists\": true } } },\n  {\n    \"$group\": {\n      \"_id\": { \"longitude\": \"$longitude\", \"latitude\": \"$latitude\" },\n      \"times\": { \"$sum\": 1 },\n      \"data\": { \"$first\": \"$$ROOT\" }\n    }\n  },\n  { \"$replaceRoot\": { \"newRoot\": { \"$mergeObjects\": [ \"$data\", { \"times\": \"$times\" } ] } } },\n  { \"$project\": { \"eventid\": 1, \"duration\": 1, \"message\": 1, \"timestamp\": 1, \"src_ip\": 1, \"latitude\": 1, \"longitude\": 1, \"times\": 1, \"username\": 1, \"password\": 1, \"hash\": 1 } },\n  { \"$sort\": { \"timestamp\": -1 } },\n  { \"$limit\": 2000 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  {\n    \"$group\": {\n      \"_id\": \"$src_ip\"\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": null,\n      \"Unique IPs\": { \"$sum\": 1 }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  {\n    \"$match\": {\n      \"eventid\": \"cowrie.session.file_download\"\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": null,\n      \"totalFiles\": { \"$sum\": 1 },\n      \"uniqueFiles\": { \"$addToSet\": \"$shasum\" }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"Total files\": \"$totalFiles\",\n      \"Unique files\": { \"$size\": \"$uniqueFiles\" }\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  {\n    \"$match\": { \"tor\": true }\n  },\n  {\n    \"$group\": {\n      \"_id\": \"$src_ip\"\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": null,\n      \"count\": { \"$sum\": 1 }\n    }\n  }\n]\n)",
     "type": "table"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  { \"$group\": { \"_id\": null, \"totalConnections\": { \"$sum\": 1 } } },\n  { \"$project\": { \"_id\": 0, \"totalConnections\": 1 } }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  { \"$match\": { \"eventid\": \"cowrie.command.input\" } },\n  { \"$group\": { \"_id\": null, \"count\": { \"$sum\": 1 } } }\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "Top 10 countries (all-time)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  { \"$match\": { \"country\": { \"$exists\": true } } },\n  { \"$group\": { \"_id\": \"$country\", \"count\": { \"$sum\": 1 } } },\n  { \"$sort\": { \"count\": -1 } },\n  { \"$limit\": 10 },\n  { \"$project\": { \"country\": \"$_id\", \"attacks\": \"$count\", \"_id\": 0 } }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Top 10 commands",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  {\n    \"$match\": {\n      \"eventid\": \"cowrie.command.input\"\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": \"$input\",\n      \"count\": { \"$sum\": 1 }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"input\": \"$_id\",\n      \"count\": 1\n    }\n  },\n  {\n    \"$sort\": {\n      \"count\": -1\n    }\n  },\n  {\n    \"$limit\": 10\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daytime/Night-time (from machine)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  { \"$limit\": 50000 },\n  {\n    \"$project\": {\n      \"timestamp\": 1,\n      \"isNight\": {\n        \"$cond\": [\n          {\n            \"$or\": [\n              { \"$gte\": [{ \"$hour\": { \"$toDate\": \"$timestamp\" } }, 20] },\n              { \"$lt\": [{ \"$hour\": { \"$toDate\": \"$timestamp\" } }, 6] }\n            ]\n          },\n          true,\n          false\n        ]\n      },\n      \"isDay\": {\n        \"$cond\": [\n          {\n            \"$and\": [\n              { \"$gte\": [{ \"$hour\": { \"$toDate\": \"$timestamp\" } }, 6] },\n              { \"$lt\": [{ \"$hour\": { \"$toDate\": \"$timestamp\" } }, 20] }\n            ]\n          },\n          true,\n          false\n        ]\n      }\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": null,\n      \"Daytime attacks\": { \"$sum\": { \"$cond\": [\"$isNight\", 1, 0] } },\n      \"Night-time attacks \": { \"$sum\": { \"$cond\": [\"$isDay\", 1, 0] } }\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Local time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 17 },
   "targets": [
    { "target": "select metric", "type": "timeserie" }
   ]
  },
  {
   "title": "Daytime/Night-time  (from source)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  { \"$limit\": 50000 },\n  {\n    \"$project\": {\n      \"attacker_timestamp\": 1,\n      \"isNight\": {\n        \"$cond\": [\n          {\n            \"$or\": [\n              { \"$gte\": [{ \"$hour\": { \"$toDate\": \"$attacker_timestamp\" } }, 20] },\n              { \"$lt\": [{ \"$hour\": { \"$toDate\": \"$attacker_timestamp\" } }, 6] }\n            ]\n          },\n          true,\n          false\n        ]\n      },\n      \"isDay\": {\n        \"$cond\": [\n          {\n            \"$and\": [\n              { \"$gte\": [{ \"$hour\": { \"$toDate\": \"$attacker_timestamp\" } }, 6] },\n              { \"$lt\": [{ \"$hour\": { \"$toDate\": \"$attacker_timestamp\" } }, 20] }\n            ]\n          },\n          true,\n          false\n        ]\n      }\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": null,\n      \"Daytime attacks\": { \"$sum\": { \"$cond\": [\"$isNight\", 1, 0] } },\n      \"Night-time attacks\": { \"$sum\": { \"$cond\": [\"$isDay\", 1, 0] } }\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "File Captures",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  {\n    \"$match\": {\n      \"eventid\": \"cowrie.session.file_download\"\n    }\n\n  },\n  {\n    \"$sort\": {\n      \"timestamp\": -1\n    }\n  },\n  {\n    \"$project\": {\n      \"from\": \"$src_ip\",\n      \"country\": \"$country\",\n      \"honeypot\": \"$source\",\n      \"timestamp\": \"$timestamp\",\n      \"file-hash\": \"$shasum\",\n      \"scan\": \"$virustotal\",\n      \"_id\": 0\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Malware sources",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  {\n    \"$match\": {\n      \"eventid\": \"cowrie.command.input\"\n    }\n  },\n  {\n    \"$project\": {\n      \"honeypot\": \"$source\",\n      \"_id\": 0,\n      \"src_ip\": \"$src_ip\",\n      \"input\": {\n        \"$let\": {\n          \"vars\": {\n            \"httpLink\": {\n              \"$regexFind\": {\n                \"input\": \"$input\",\n                \"regex\": \"(https?://\\\\S+)\"\n              }\n            }\n          },\n          \"in\": \"$$httpLink.match\"\n        }\n      }\n    }\n  },\n  {\n    \"$match\": {\n      \"input\": { \"$ne\": null }\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": \"$input\",\n      \"times used\": { \"$sum\": 1 },\n      \"src_ip\": { \"$first\": \"$src_ip\" }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"end point\": \"$_id\",\n      \"times run\": \"$times_run\",\n      \"from\": \"$src_ip\",\n      \"times used\": 1,\n\n    }\n  },\n  {\n    \"$sort\": {\n      \"times used\": -1\n    }\n  },\n  {\n    \"$limit\": 10\n  }\n]);",
     "type": "table"
    },
    { "target": "select metric", "type": "timeserie" }
   ]
  },
  {
   "title": "Most common passwords",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 37 },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  { \"$group\": { \"_id\": \"$password\", \"count\": { \"$sum\": 1 } } },\n  { \"$sort\": { \"count\": -1 } },\n  { \"$skip\": 1 },\n  { \"$limit\": 50 },\n  { \"$project\": { \"Password\": \"$_id\", \"Occurrencies\": \"$count\", \"_id\": 0 } }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Most common usernames",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 37 },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  { \"$group\": { \"_id\": \"$username\", \"count\": { \"$sum\": 1 } } },\n  { \"$sort\": { \"count\": -1 } },\n  { \"$skip\": 1 },\n  { \"$limit\": 50 },\n  { \"$project\": { \"Username\": \"$_id\", \"Occurrences\": \"$count\", \"_id\": 0 } }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Latest run commands",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "target": "db.HON1.aggregate([\n  {\n    \"$match\": {\n      \"eventid\": \"cowrie.command.input\"\n    }\n  },\n  {\n    \"$sort\": {\n      \"timestamp\": -1\n    }\n  },\n  {\n    \"$project\": {\n      \"honeypot\": \"$source\",\n      \"_id\": 0,\n      \"input\": 1,\n       \"timestamp\":1,\n      \"from\": \"$src_ip\"\n    }\n  },\n  {\n    \"$limit\": 50\n  }\n])",
     "type": "table"
    }
   ]
  }
 ]
}