{
 "title": "Timeseries Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cowrie Honeypot Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total SSH connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "Cowrie_SSH_connections{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": " Total & Accepted SSH Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "Cowrie_SSH_connections{instance=\"localhost:8001\"}",
     "legendFormat": "Total connections"
    },
    {
     "expr": "Cowrie_SSH_accepted_connections{instance=\"localhost:8001\"}",
     "legendFormat": "Accepted connections"
    }
   ]
  },
  {
   "title": " Refused SSH Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "Cowrie_SSH_connections{instance=\"localhost:8001\"}"
    },
    {
     "expr": "Cowrie_SSH_accepted_connections{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": " Accepted SSH Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "Cowrie_SSH_accepted_connections{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": " Downloaded files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 31 },
   "targets": [
    {
     "expr": "Cowrie_downloads{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": "Run SSH commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "Cowrire_SSH_commands{instance=\"localhost:8001\"}"
    }
   ]
  },
  { "title": "Dionaea Honeypot Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Dionaea HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Dionaea_HTTP_connections{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "SMB Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "Dionaea_SMB_connections{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "FTP & SMB uploaded files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 51 },
   "targets": [
    {
     "expr": "Dionaea_downloads{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "FTP Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "Dionaea_FTP_connections{instance=\"localhost:8002\"}"
    }
   ]
  },
  { "title": "VM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "VM NETWORK TX",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "VM_NET_TX{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": "VM NETWORK RX",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "VM_NET_RX{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": "VM Kernel CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "VM_CPU_Kernel{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": "VM User CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "VM_CPU_User{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": "VM RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "VM_RAM_Usage{instance=\"localhost:8001\"}"
    }
   ]
  }
 ]
}