{
 "title": "Timeseries_Dashboard (Docker)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cowrie Honeypot Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SSH Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "Cowrie_SSH_connections{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": "Total & Accepted SSH Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "Cowrie_SSH_connections{instance=\"localhost:8001\"}",
     "legendFormat": "Total Connections"
    },
    {
     "expr": "Cowrie_SSH_accepted_connections{instance=\"localhost:8001\"}",
     "legendFormat": "Accepted  Connections"
    }
   ]
  },
  {
   "title": "Refused SSH connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "Cowrie_SSH_connections{instance=\"localhost:8001\"}",
     "legendFormat": "Total Connections"
    },
    {
     "expr": "Cowrie_SSH_accepted_connections{instance=\"localhost:8001\"}",
     "legendFormat": "Accepted  Connections"
    }
   ]
  },
  {
   "title": "Accepted SSH Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "Cowrie_SSH_accepted_connections{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": "Downloaded files ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 31 },
   "targets": [
    {
     "expr": "Cowrie_downloads{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": "run SSH commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "Cowrire_SSH_commands{instance=\"localhost:8001\"}"
    }
   ]
  },
  { "title": "Dionaea Honeypot HON1 AWS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "HTTP Requests ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "Dionaea_HTTP_connections{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "SMB Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "Dionaea_SMB_connections{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "FTP & SMB uploaded files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 51 },
   "targets": [
    {
     "expr": "Dionaea_downloads{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "FTP Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "Dionaea_FTP_connections{instance=\"localhost:8002\"}"
    }
   ]
  },
  { "title": "Dionaea Docker stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Docker CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DIONAEA_DOCKER_CPU_Load{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "Docker RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 71 },
   "targets": [
    { "expr": "DIONAEA_DOCKER_RAM_Usage" }
   ]
  },
  { "title": "COWRIE DOCKER STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Docker CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "COWRIE_DOCKER_CPU_Load{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": "Docker RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "COWRIE_DOCKER_RAM_Usage{instance=\"localhost:8001\"}"
    }
   ]
  }
 ]
}