{
 "title": "Z-score",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cowrie Honeypot Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Z-Score SSH connections",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "Cowrire_SSH_Cowrie_connections_zscore{instance=\"localhost:8001\"}",
     "legendFormat": "Z-score"
    }
   ]
  },
  {
   "title": " Accepted SSH Connections Z-score",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "Cowrire_SSH_Cowrie_accepted_zscore{instance=\"localhost:8001\"}"
    }
   ]
  },
  {
   "title": " Downloaded files Z-score",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "Cowrie_downloads{instance=\"localhost:8001\"}",
     "legendFormat": "Z-score"
    }
   ]
  },
  {
   "title": "Run SSH commands Z-score",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "Cowrire_SSH_commands{instance=\"localhost:8001\"}"
    }
   ]
  },
  { "title": "Dionaea Honeypot Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Z-score HTTP connections",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "Dionaea_HTTP_connections_zscore{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "SMB Connections Z-score",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "Cowrire_SSH_Cowrie_connections_smb_zscore{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "FTP & SMB uploaded files Z-score",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 31 },
   "targets": [
    {
     "expr": "Dionaea_downloads_zscore{instance=\"localhost:8002\"}"
    }
   ]
  },
  {
   "title": "FTP Connections Z-score",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "Cowrire_SSH_Cowrie_connections_ftp_zscore{instance=\"localhost:8002\"}"
    }
   ]
  },
  { "title": "VM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}