# CONFIGURATION FILE (CHANGE WITH YOUR INFLUXDB DATA)

INFLUXDB_TOKEN = 'Sjw-tnzb3mKiRoQMfSEi_3pjT7Q2ewL3SUSNStqBJX0WtjP5RsPuLXl75iJXIrVQ7FYX_RijAGI2zxhslPKtQA=='

INFLUXDB_BUCKET = 'system_monitor'

INFLUXDB_ORGANIZATION ='gestionereti'
