{
 "title": "Netmon Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Netmon status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"netmon\"} == bool 1",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total collection errors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "netmon_collection_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Service counter by protocol",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netmon_services{protocol=\"tcp\"}",
     "legendFormat": "Number of {{protocol}} services"
    },
    {
     "expr": "netmon_services{protocol=\"udp\"}",
     "legendFormat": "Number of {{protocol}} services"
    }
   ]
  },
  {
   "title": "Tcp service list",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "netmon_service_up{job=\"netmon\", protocol=\"tcp\"}",
     "legendFormat": "{{process}}:{{port}}"
    }
   ]
  },
  {
   "title": "Number of open events last 5m",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(netmon_open_events_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds between scans",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - netmon_last_success_timestamp_seconds ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of close events last 5m",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(netmon_close_events_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 6, "y": 13 },
   "targets": [
    { "expr": "netmon_process_services", "legendFormat": "{{process}}:{{protocol}}" }
   ]
  },
  {
   "title": "Udp service list",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "netmon_service_up{job=\"netmon\", protocol=\"udp\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}