{
 "title": "Counters",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Traffico byte",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Bytes IN: [[tag_ifIndex]]@[[tag_Agent]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Agent" ], "type": "tag" },
      { "params": [ "ifIndex" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Flow",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Bytes OUT: [[tag_ifIndex]]@[[tag_Agent]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Agent" ], "type": "tag" },
      { "params": [ "ifIndex" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Flow",
     "select": [
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume traffico pacchetti",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pkts IN: [[tag_ifIndex]]@[[tag_Agent]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Flow",
     "query": "SELECT non_negative_difference(mean(\"ifInUcastPkts\"))+non_negative_difference(mean(\"ifInMulticastPkts\"))+non_negative_difference(mean(\"ifInErrors\"))+non_negative_difference(mean(\"ifInDiscards\"))+non_negative_difference(mean(\"ifInUnknownProtos\"))+non_negative_difference(mean(\"ifInBroadcastPkts\")) FROM \"Flow\" WHERE $timeFilter GROUP BY time($__interval), \"Agent\", \"ifIndex\" fill(null)",
     "select": [
      [
       { "params": [ "ifInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ],
      [
       { "params": [ "ifInMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ],
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ],
      [
       { "params": [ "ifInDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Pkts OUT: [[tag_ifIndex]]@[[tag_Agent]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Flow",
     "query": "SELECT non_negative_difference(mean(\"ifOutBroadcastPkts\"))+non_negative_difference(mean(\"ifOutUcastPkts\"))+non_negative_difference(mean(\"ifOutMulticastPkts\"))-non_negative_difference(mean(\"ifOutErrors\"))-non_negative_difference(mean(\"ifOutDiscards\")) FROM \"Flow\" WHERE $timeFilter GROUP BY time($__interval), \"Agent\", \"ifIndex\" fill(null)",
     "select": [
      [
       { "params": [ "ifOutBroadcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ],
      [
       { "params": [ "ifOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ],
      [
       { "params": [ "ifOutMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ],
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ],
      [
       { "params": [ "ifOutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Utilizzo banda",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Bandwidth: [[tag_ifIndex]]@[[tag_Agent]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Flow",
     "query": "SELECT ((non_negative_difference(mean(\"ifOutOctets\"))+non_negative_difference(mean(\"ifInOctets\")))*800)/(mean(\"ifSpeed\")*20) FROM \"Flow\" WHERE $timeFilter GROUP BY time($__interval), \"Agent\", \"ifIndex\" fill(null)",
     "select": [
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ],
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Usage IN: [[tag_ifIndex]]@[[tag_Agent]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Flow",
     "query": "SELECT (non_negative_difference(mean(\"ifInOctets\"))*800)/(20*(mean(\"ifSpeed\"))) FROM \"Flow\" WHERE $timeFilter GROUP BY time($__interval), \"Agent\", \"ifIndex\" fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Usage OUT: [[tag_ifIndex]]@[[tag_Agent]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (non_negative_difference(mean(\"ifOutOctets\"))*800)/(20*(mean(\"ifSpeed\"))) FROM \"Flow\" WHERE $timeFilter GROUP BY time($__interval), \"Agent\", \"ifIndex\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}