{
 "title": "Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Pacchetti ricevuti/s, media 1 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{job=\"node\", device=\"en0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pacchetti trasmessi/s, media 1 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{job=\"node\", device=\"en0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Byte ricevuti/s, media 1 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node\", device=\"en0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Byte trasmessi/s, media 1 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node\", device=\"en0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilizzo CPU (%), media 1 min",
   "type": "timeseries",
   "description": "CPU usata = 100 * (1- CPU idle)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "100 * (1- avg by (instance) (rate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoria usata (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes{job=\"node\"} /node_memory_MemTotal_bytes{job=\"node\"})\nor\n100 * (1 - (node_memory_free_bytes{job=\"node\"} + node_memory_inactive_bytes{job=\"node\"}) / node_memory_total_bytes{job=\"node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert attivi ",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ALERTS",
     "legendFormat": "{{alertname}} - {{alertstate}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Stato node_exporter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "up{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storico alert firing",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum by (alertname) (ALERTS{alertstate=\"firing\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}