Balanced PF_RING Dispatcher: BPFRD::BalOutIface Class Reference
BPFRD::BalOutIface Class Reference
Represent an output interfaces used by the balancer.
#include <BalOutIface.h>
Public Member Functions
BalOutIface (string ifName, unsigned int refreshTime=10)
Represent an output interface adapt to load balancing.
int open ()
Open the interface for sending packets.
void close ()
Close the interface.
string getIfName ()
Get linux interface name.
int send (char *pkt, size_t lenght)
Send given packet throught the interface.
Static Public Member Functions
static bool compare (BalOutIface *oIf1, BalOutIface *oIf2)
Compare one interface to another by freshTxPkts.
Static Protected Member Functions
static void * refreshTxPkts (void *arg)
Reset freshTxPkts counter to 0 approssimatively each refreshTime seconds.
Protected Attributes
string ifName
Stores the linux ifname to wich the BalOutIface is attacched.
pfring * outRing
Pointer to the pf_ring output ring attacched to ifName.
bool closed
True if the interface is closed flase otherways.
pthread_t * refreshThread
Pointer tho the thread that reset the freshTxPkts counter.
unsigned int refreshTime
Seconds between freshTxPkts reset.
unsigned long long freshTxPkts
Number of recently sended packets.
Detailed Description
Represent an output interfaces used by the balancer.
Constructor & Destructor Documentation
BalOutIface::BalOutIface (string ifName, unsigned int refreshTime = 10)
Represent an output interface adapt to load balancing.
Parameters:
ifName Linux interface name
refreshTime Time in seconds after packet count get resetted
References closed, freshTxPkts, ifName, outRing, PDEBUG, refreshThread, and refreshTime.
Member Function Documentation
static bool BPFRD::BalOutIface::compare (BalOutIface * oIf1, BalOutIface * oIf2) [inline, static]
Compare one interface to another by freshTxPkts.
Parameters:
oIf1 first interface
oIf2 second interface
Returns:
true if oIf1 has sent less packet than oIf2, false otherwise
References freshTxPkts.
Referenced by BPFRD::PacketDispatcher::dispatch().
string BPFRD::BalOutIface::getIfName ()
Get linux interface name.
Returns:
A string containing the linux interface name
int BalOutIface::open ()
Open the interface for sending packets.
Returns:
1 if evreything goes fine
2 if the interface was already open
-1 if error occurred while opening the interface
References closed, freshTxPkts, ifName, outRing, PDEBUG, refreshThread, and refreshTxPkts().
Referenced by main().
void * BalOutIface::refreshTxPkts (void * arg) [static, protected]
Reset freshTxPkts counter to 0 approssimatively each refreshTime seconds.
Parameters:
arg The this pointer must be passed as arg as the function is static
Referenced by open().
int BPFRD::BalOutIface::send (char * pkt, size_t lenght) [inline]
Send given packet throught the interface.
Parameters:
pkt Packet to send
lenght Lenght of the packet to send
Returns:
pfring_send return value if passed param are correct or FUNC_PARAM_CHECKING is undefined
0 if FUNC_PARAM_CHECKING is defined and passed param are wrong
References PDEBUG.
Referenced by BPFRD::PacketDispatcher::dispatch().
The documentation for this class was generated from the following files:
BalOutIface.h
BalOutIface.cpp