Balanced PF_RING Dispatcher: BPFRD::PacketDispatcher Class Reference
BPFRD::PacketDispatcher Class Reference
Represent The Dispatcher.
#include <PacketDispatcher.h>
Public Member Functions
PacketDispatcher (DispatchingModes dispatchingMode, list< BalOutIface * > *outIfList, unsigned int _tableSize=1024, unsigned int agingTime=600)
Initialize PacketDispatcher.
void dispatch (char *pkt, struct pfring_pkthdr *hdr)
dispatch dispatch packet
Static Protected Member Functions
static void * timedCleanTable (void *arg)
Hash table cleaner loop.
static unsigned int hash (DispatchingModes hashingMode, char *buffer, unsigned int buffer_len, unsigned int mask)
function to be called to hash packets
static unsigned int ipHash (char buffer[], unsigned int buffer_len, unsigned int mask)
Source and destination IP hashing function.
static unsigned int ippHash (char buffer[], unsigned int buffer_len, unsigned int mask)
Source IP, destination IP, transport protocol, source port, destination port hashing function.
Protected Attributes
DispatchingModes dspMode
selected dispatching mode
unsigned int tableSize
real flow hash table size
unsigned int tableSizeMask
mask used for fast hashing
unsigned int agingTime
time in seconds between periodical flow hash table cleanings
HashTableElement * fluxTable
pointer to flow hash table
list< BalOutIface * > * outIfList
pointer to output interface list
pthread_t * refreshThread
pointer to flow hash table cleaner thread
Static Protected Attributes
static const unsigned int hashingModesNum = 2
Number of hashing modes available.
static const ptHashFunc hasherArray [hashingModesNum] = { ipHash, ippHash }
Array of pointers to the available hashing function.
Detailed Description
Represent The Dispatcher.
Constructor & Destructor Documentation
PacketDispatcher::PacketDispatcher (DispatchingModes dispatchingMode, list< BalOutIface * > * outIfList, unsigned int _tableSize = 1024, unsigned int agingTime = 600)
Initialize PacketDispatcher.
Parameters:
dispatchingMode chosen dispatching mode from DispatchingModes enum
outIfList list of output interface
_tableSize size of hashtable (will be rounded to next power of 2)
agingTime time in seconds between periodical flow hash table cleanings
References agingTime, dspMode, fluxTable, outIfList, refreshThread, tableSize, tableSizeMask, and timedCleanTable().
Member Function Documentation
void BPFRD::PacketDispatcher::dispatch (char * pkt, struct pfring_pkthdr * hdr) [inline]
dispatch dispatch packet
Parameters:
pkt packet
hdr pfring packet header
References BPFRD::BalOutIface::compare(), dspMode, fluxTable, hash(), BPFRD::HashTableElement::lastMatch, BPFRD::HashTableElement::outIf, BPFRD::BalOutIface::send(), and unlikely.
Referenced by main().
static unsigned int BPFRD::PacketDispatcher::hash (DispatchingModes hashingMode, char * buffer, unsigned int buffer_len, unsigned int mask) [inline, static, protected]
function to be called to hash packets
Parameters:
hashingMode hashing mode
buffer packet to be hashed
buffer_len packet lenght
mask mask for fast hashing
Returns:
packet hash
References hasherArray, hashingModesNum, and unlikely.
Referenced by dispatch(), ipHash(), and ippHash().
static unsigned int BPFRD::PacketDispatcher::ipHash (char buffer[], unsigned int buffer_len, unsigned int mask) [inline, static, protected]
Source and destination IP hashing function.
Parameters:
buffer packet to hash
buffer_len packet lenght
mask
Returns:
pachet hash
References hash(), PDEBUG, and unlikely.
static unsigned int BPFRD::PacketDispatcher::ippHash (char buffer[], unsigned int buffer_len, unsigned int mask) [inline, static, protected]
Source IP, destination IP, transport protocol, source port, destination port hashing function.
Parameters:
buffer packet to hash
buffer_len packet lenght
mask mask for fast hashing
Returns:
packet hash
References hash(), PDEBUG, and unlikely.
void * PacketDispatcher::timedCleanTable (void * arg) [static, protected]
Hash table cleaner loop.
Parameters:
arg A pointer to PacketDispatcher must be passed as argument because the function is static to be referanceable
Referenced by PacketDispatcher().
The documentation for this class was generated from the following files:
PacketDispatcher.h
PacketDispatcher.cpp