{
 "title": "ntopng - network status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scores and suspicious activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host scores",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "host:score",
       "select": [
        [
         { "params": [ "score" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DNS ratio",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$B / ($A + ($A == 0))", "type": "math" }
     ]
    },
    {
     "title": "AVG received packet dimension",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expression": "$rcvd_traffic / ($TCP_rcvd_packets + $UDP_rcvd_packets + ($TCP_rcvd_packets + $UDP_rcvd_packets == 0))",
       "type": "math"
      }
     ]
    },
    {
     "title": "AVG sent packet dimension",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expression": "$sent_traffic / ($TCP_sent_packets + $UDP_sent_packets + ($TCP_sent_packets + $UDP_sent_packets == 0))",
       "type": "math"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host traffic sent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "host:traffic",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Host traffic received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "host:traffic",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "L4 protocols",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP vs UDP",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_l4proto",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "l4proto" ], "type": "tag" }
       ],
       "measurement": "iface:l4protos",
       "select": [
        [
         { "params": [ "bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "l4proto", "operator": "=", "value": "tcp" },
        { "condition": "OR", "key": "l4proto", "operator": "=", "value": "udp" }
       ]
      }
     ]
    },
    {
     "title": "Protocol Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_l4proto",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "l4proto" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "host:l4protos",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ethernet interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet interface traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "iface:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes\"), 1s)  *8 FROM \"autogen\".\"iface:traffic\" WHERE (\"ifid\" = '0') AND $timeFilter GROUP BY time(1s)",
       "select": [
        [
         { "params": [ "bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "ifid", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Ethernet interface speed",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iface:traffic",
       "select": [
        [
         { "params": [ "bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "ifid", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Ethernet interface total traffic",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" }
       ],
       "measurement": "iface:traffic",
       "query": "SELECT last(\"bytes\") FROM \"autogen\".\"iface:traffic\" WHERE (\"ifid\" = '2') AND $timeFilter GROUP BY time(10s)",
       "select": [
        [
         { "params": [ "bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "ifid", "operator": "=", "value": "2" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Flows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active flows per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expression": "$A + $B", "type": "math" }
     ]
    },
    {
     "title": "Total host flows",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Flows" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expression": "$A + $B", "type": "math" }
     ]
    },
    {
     "title": "Total flows on ethernet interface",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Flows" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iface:flows",
       "select": [
        [
         { "params": [ "num_flows" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Contacted hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of hosts contacted as client",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "host:contacts",
       "select": [
        [
         { "params": [ "num_as_client" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of hosts contacted as server",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "host:contacts",
       "select": [
        [
         { "params": [ "num_as_server" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Traffic rate by country",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_country",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "country:traffic",
       "select": [
        [
         { "params": [ "bytes_ingress" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ "/60" ], "type": "math" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}