{
 "title": "fixare",
 "time": { "from": "2019-07-11T13:22:03.702Z", "to": "2019-07-20T15:57:33.682Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES WITH KEY = host"
   }
  ]
 },
 "panels": [
  {
   "title": "Media Flussi Attivi per intervallo di tempo",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:active_flows",
     "query": "SELECT sum(\"flows_as_server\")+sum(\"flows_as_client\") FROM \"host:active_flows\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "flows_as_client" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nuovi Flussi misbehaving in intervallo di tempo",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "alias": "client+server derivative1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select  non_negative_difference( sum(\"flows_as_server\")) + non_negative_difference(sum( \"flows_as_client\"))  from \"host:misbehaving_flows\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Misbehaving  host timeline",
   "type": "table",
   "description": "Raccoglie li numero di flussi misbehaving  in ordine di tempo per ogni host",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Host:",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:misbehaving_flows",
     "query": "SELECT \"host\",\"flows_as_client\" AS \"n. flussi client\", \"flows_as_server\" AS \"n.flussi server\" FROM \"host:misbehaving_flows\" WHERE   \"flows_as_client\">0 OR \"flows_as_server\">0 AND $timeFilter  order by time desc",
     "select": [
      [
       { "params": [ "flows_as_client" ], "type": "field" },
       { "params": [ "client" ], "type": "alias" }
      ],
      [
       { "params": [ "flows_as_server" ], "type": "field" },
       { "params": [ "server" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "\"host\""
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nuovi flussi nell intervallo",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select sum(client)+sum(server)from(SELECT non_negative_difference( sum(\"flows_as_client\"))as \"client\",non_negative_difference( sum(\"flows_as_server\")) as \"server\" FROM \"host:total_flows\" WHERE $timeFilter GROUP BY time(1s) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New misbehaving_flows ( host )",
   "type": "graph",
   "description": "Calcola i nuovi flussi anomali dell'host selezionato ( menù tendina in alto a destra )",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "New misbehaving flow $tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:misbehaving_flows",
     "query": "SELECT non_negative_difference(sum(\"flows_as_client\"))FROM \"host:misbehaving_flows\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "flows_as_client" ], "type": "field" }
      ],
      [
       { "params": [ "host" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/192.168.1.*/" },
      { "condition": "AND", "key": "flows_as_client", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Numero Pacchetti TCP(host)",
   "type": "graph",
   "description": "Statistiche sui pacchetti IN/OUT ( Lost, Out of Order, Retransmission ) selezionare l'host interessato dal menù tendina(in alto a sinistra)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host TCP OUT",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:tcp_packets",
     "query": "SELECT non_negative_difference(sum(\"packets_sent\")) FROM \"host:tcp_packets\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s),host fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host  TCP IN",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:tcp_packets",
     "query": "SELECT non_negative_difference(sum(\"packets_rcvd\")) FROM \"host:tcp_packets\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s),host fill(null)",
     "select": [
      [
       { "params": [ "packets_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host  TCP OUT:LOST",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:tcp_tx_stats",
     "query": "SELECT non_negative_derivative(sum(\"lost_packets\"), 10s) FROM \"host:tcp_tx_stats\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s),host fill(null)",
     "select": [
      [
       { "params": [ "lost_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_host  TCP OUT: OOO",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:tcp_tx_stats",
     "query": "SELECT non_negative_derivative(sum(\"out_of_order_packets\"), 1s) FROM \"host:tcp_tx_stats\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s),host fill(null)",
     "select": [
      [
       { "params": [ "out_of_order_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_host  TCP OUT: RETR.",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:tcp_tx_stats",
     "query": "SELECT non_negative_derivative(sum(\"retransmission_packets\"), 1s) FROM \"host:tcp_tx_stats\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s) ,host fill(null)",
     "select": [
      [
       { "params": [ "retransmission_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_host  TCP IN: OOO",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:tcp_rx_stats",
     "query": "SELECT non_negative_derivative(sum(\"out_of_order_packets\"), 1s) FROM \"host:tcp_rx_stats\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s),host fill(null)",
     "select": [
      [
       { "params": [ "out_of_order_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_host  TCP IN:LOST",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:tcp_rx_stats",
     "query": "SELECT non_negative_derivative(sum(\"lost_packets\"), 1s) FROM \"host:tcp_rx_stats\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s),host fill(null)",
     "select": [
      [
       { "params": [ "lost_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_host  TCP IN: RETR",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:tcp_rx_stats",
     "query": "SELECT non_negative_derivative(sum(\"retransmission_packets\"), 1s) FROM \"host:tcp_rx_stats\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s),host fill(null)",
     "select": [
      [
       { "params": [ "retransmission_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Troughput ( host ) for all ndpi categories",
   "type": "graph",
   "description": "Calcola il troughput diviso per Categorie dell'host selezionato ( menù tendina in alto a destra )",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps", "label": "bit/sec" }
   ],
   "targets": [
    {
     "alias": "$tag_host--->$tag_category.$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "category" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(sum(\"bytes_rcvd\"), 1s)*8 AS \"IN\", non_negative_derivative(sum(\"bytes_sent\"), 1s)*8  AS \"OUT\" FROM \"host:ndpi_categories\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s), \"host\", \"category\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Troughput interfaccia per protocollo",
   "type": "graph",
   "description": "Troughput diviso per protocollo sull'intera interfaccia",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_protocol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "protocol" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi",
     "query": "SELECT non_negative_derivative(sum(\"bytes\"), 1s) * 8 FROM \"iface:ndpi\" WHERE $timeFilter GROUP BY time(1s), \"protocol\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Troughput L4 proto(host)",
   "type": "graph",
   "description": "Selezionare host dal menù tendina",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host--->$tag_l4proto.$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(sum(\"bytes_rcvd\"), 1s)*8 AS \"IN\", non_negative_derivative(sum(\"bytes_sent\"), 1s)*8  AS \"OUT\" FROM \"host:l4protos\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s), \"host\", \"l4proto\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Troughput L4 proto on interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_l4proto",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:l4protos",
     "query": "SELECT non_negative_derivative( sum(\"bytes\"),1s) *8  FROM \"iface:l4protos\"  WHERE  $timeFilter GROUP BY \"l4proto\", time(1s) fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "l4proto", "operator": "=", "value": "icmp" }
     ]
    }
   ]
  }
 ]
}