CREATE VIEW IF NOT EXISTS chiba.host_dst_view AS
SELECT 
    TIME_BUCKET,
    DSTADDR,
    uniqMerge(UNIQUE_SRCADDR) AS UNIQUE_SRCADDR,
    minMerge(EXACT_START) AS EXACT_START,
    maxMerge(EXACT_END) AS EXACT_END,
    sumMerge(TOTAL_DPKTS) AS TOTAL_DPKTS,
    sumMerge(TOTAL_DOCTETS) AS TOTAL_DOCTETS
FROM chiba.host_dst_agg
GROUP BY (TIME_BUCKET, DSTADDR);

CREATE VIEW IF NOT EXISTS chiba.host_src_view AS
SELECT 
    TIME_BUCKET,
    SRCADDR,
    uniqMerge(UNIQUE_DSTADDR) AS UNIQUE_DSTADDR,
    minMerge(EXACT_START) AS EXACT_START,
    maxMerge(EXACT_END) AS EXACT_END,
    sumMerge(TOTAL_DPKTS) AS TOTAL_DPKTS,
    sumMerge(TOTAL_DOCTETS) AS TOTAL_DOCTETS,
    uniqExactMerge(UNIQUE_DSTPORT) AS UNIQUE_DSTPORT,
    PROT
FROM chiba.host_src_agg
GROUP BY (TIME_BUCKET, SRCADDR, PROT);

CREATE VIEW IF NOT EXISTS chiba.service_view AS
SELECT 
    TIME_BUCKET,
    uniqMerge(UNIQUE_SRCADDR) AS UNIQUE_SRCADDR,
    minMerge(EXACT_START) AS EXACT_START,
    maxMerge(EXACT_END) AS EXACT_END,
    sumMerge(TOTAL_DPKTS) AS TOTAL_DPKTS,
    sumMerge(TOTAL_DOCTETS) AS TOTAL_DOCTETS,
    DSTPORT,
    PROT
FROM chiba.service_agg
GROUP BY (TIME_BUCKET, DSTPORT, PROT);

CREATE VIEW IF NOT EXISTS chiba.slow_scanners_view AS
SELECT 
    SRCADDR,
    uniqExactMerge(UNIQUE_DSTPORT) AS UNIQUE_DSTPORT,
    uniqMerge(UNIQUE_DSTADDR) AS UNIQUE_DSTADDR,
    minMerge(EXACT_START) AS EXACT_START,
    maxMerge(EXACT_END) AS EXACT_END,
    sumMerge(TOTAL_DPKTS) AS TOTAL_DPKTS,
    sumMerge(TOTAL_DOCTETS) AS TOTAL_DOCTETS,
    dateDiff('minute', toDateTime(EXACT_START), toDateTime(EXACT_END)) AS ACTIVE_SPAN_MINUTES,
    round(UNIQUE_DSTPORT / greatest(1, (EXACT_END - EXACT_START) / 3600), 2) AS PORTS_PER_HOUR
FROM chiba.host_src_agg
WHERE TIME_BUCKET >= now() - INTERVAL 24 HOUR
GROUP BY SRCADDR
HAVING (UNIQUE_DSTPORT >= 50 OR UNIQUE_DSTADDR >= 100)
   AND ACTIVE_SPAN_MINUTES >= 30;
