{
 "title": "Linux PC Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Instantaneous CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - ((irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[10s])) * 100)",
     "legendFormat": "Cpu {{cpu}} - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m]) * 100",
     "legendFormat": "Cpu {{cpu}} - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(avg by (chip)(node_hwmon_temp_celsius{job=\"node\"}))",
     "legendFormat": "Chip {{chip}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (100 * ((avg_over_time(node_memory_Buffers_bytes{job=\"node\"}[1m]) + avg_over_time(node_memory_MemFree_bytes{job=\"node\"}[1m]) + avg_over_time(node_memory_Cached_bytes{job=\"node\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{job=\"node\"}[1m])))",
     "legendFormat": "RAM - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\"}",
     "legendFormat": "Free Space"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\"}",
     "legendFormat": "Used Space"
    }
   ]
  },
  {
   "title": "Network Bytes In/Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\"}[15s])",
     "legendFormat": "Device {{device}} (Received) - {{instance}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\"}[15s])",
     "legendFormat": "Device {{device}} (Transmitted) - {{instance}}"
    }
   ]
  }
 ]
}