# Disable DNS service offered by dnsmasq.
port=0
interface=eth0
dhcp-range=192.168.100.10,192.168.100.160,12h
dhcp-leasefile=/var/lib/misc/dnsmasq.leases.raw
# Call the script at each add, old, del event.
dhcp-script=/usr/local/bin/lease-hook.sh
# Include extra needed file.
conf-dir=/etc/dnsmasq.d/,*.conf
log-dhcp
# Send log to stdout/stderr instead of syslog.
log-facility=-
