default-lease-time 43200;
max-lease-time 43200;
authoritative;
# Disable DNS dynamic updates.
ddns-update-style none;

include "/etc/dhcp/dhcpd.whitelist-hosts.conf";

subnet 192.168.100.0 netmask 255.255.255.0 {
  option subnet-mask 255.255.255.0;
  option broadcast-address 192.168.100.255;
  option routers 192.168.100.1;

  pool {
    include "/etc/dhcp/dhcpd.whitelist-policy.conf";
    range 192.168.100.10 192.168.100.160;
  }
}
