{
 "title": "Cluster Docker Metrics",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (name)(rate(container_cpu_usage_seconds_total{name=~\".+\"}[40s]))) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum by (name)(container_memory_usage_bytes{name=~\".+\"})) * 100) / ignoring (name) group_left sum(machine_memory_bytes{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}} storage used"
    }
   ]
  },
  {
   "title": "Container Network Bytes In/Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum by (name)(irate(container_network_receive_bytes_total{name=~\".+\"}[15s])))",
     "legendFormat": "Received {{name}}"
    },
    {
     "expr": "(sum by (name)(irate(container_network_transmit_bytes_total{name=~\".+\"}[15s])))",
     "legendFormat": "Transmitted {{name}}"
    }
   ]
  }
 ]
}