/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpcap_JpcapWriter */

#ifndef _Included_jpcap_JpcapWriter
#define _Included_jpcap_JpcapWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpcap_JpcapWriter
 * Method:    nativeOpenDumpFile
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpcap_JpcapWriter_nativeOpenDumpFile
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     jpcap_JpcapWriter
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jpcap_JpcapWriter_close
  (JNIEnv *, jobject);

/*
 * Class:     jpcap_JpcapWriter
 * Method:    writePacket
 * Signature: (Ljpcap/packet/Packet;)V
 */
JNIEXPORT void JNICALL Java_jpcap_JpcapWriter_writePacket
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
