exe: main.cpp blacklist.hpp  collector.hpp  dataflows.hpp  emitter.hpp  netdevice.hpp  packet.hpp  state.hpp worker.hpp Makefile
	g++ -g -I mc-fastflow/ main.cpp -o exe -lpcap -lpthread -std=c++0x
	


